### ISSUE TITLE
Cacti results

### ISSUE THREAD

**Issue by Sacusa** [TeCSAR-UNCC/gem5-SALAM#13]
It looks like the CACTI power and area results are still under development. In the current master branch, the only reason I see it is broken is that `getReadBusWidth` in [comm_interface.cc](https://github.com/TeCSAR-UNCC/gem5-SALAM/blob/5003c58879f1812c84959fc412bcfcbf01c53caf/src/hwacc/comm_interface.hh#L252) returns a 0, causing the `word_size` parameter to [getCactiResults](https://github.com/TeCSAR-UNCC/gem5-SALAM/blob/5003c58879f1812c84959fc412bcfcbf01c53caf/src/hwacc/LLVMRead/src/utilization.cc#L385) to be set to 0, which causes an infinite loop in CACTI. Is there any timeline for updating this and verification of the setting of other parameters?

EDIT: looks like `getReadPorts`, `getWritePorts`, `getWriteBusWidth`, and `getPmemRange` return 0 too.

**Comment by Josh-Slycord** [comment]
The CACTI integration did once work in V1, it was disabled to allow expansion work on comm_interface and as the whole project moved forward into V2 it was never re-implemented. I am almost certain I have a backup of the source code from when CACTI was functioning, I will be able to check this Thursday when I'm back in the lab and update this thread. In general V1 became a sort of test-bed for the code for V2, and it was an oversight to not maintain a stable side branch. That being said, V2 will be far superior to V1, and there is no further development beyond bug-fixes and pull requests planned for V1 by our team.

**Comment by Sacusa** [comment]
It will be great if I can have a look at the functioning CACTI code, thanks!

**Comment by zephan-spencer** [comment]
Going to close this for now as well as I know there were offline discussions for this. If still an issue we can re-open it.
