### ISSUE TITLE
Support for more topologies

### ISSUE THREAD

**Issue by Sacusa** [TeCSAR-UNCC/gem5-SALAM#15]
In its current state, each accelerator cluster is connected by two crossbar networks, one coherent and the other not. Is there any plan to support more topologies going forward, perhaps with Ruby?

**Comment by zephan-spencer** [comment]
Right now we probably aren't going to be changing this up, but this should be easily changed with modifications to the configurator. If there's a specific use case that you have in mind, demonstrating it visually would be helpful to get an idea of what would be needed to implement on our side.

I'm also not sure if Sam has already gotten around to addressing this offline, so I'm going to go ahead and close this issue for now. We can re-open it if still relevant.
