### ISSUE TITLE
IndexError: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

### ISSUE THREAD

**Issue by ayush-upc** [TeCSAR-UNCC/gem5-SALAM#2]
Hey, I am new to SALAM. I followed the instructions given and tried to run stencil2d benchmark on ARM architecture. I got the following output:

em5 Simulator System.  http://gem5.org
gem5 is copyrighted software; use the --copyright option for details.
gem5 compiled Dec 13 2020 18:02:09
gem5 started Dec 14 2020 13:24:07
gem5 executing on arcogtx980ti, pid 31865
command line: /scratch/ayush/test/gem5-SALAM/build/ARM/gem5.opt --debug-flags=HWACC --outdir=BM_ARM_OUT/sys_validation/stencil2d configs/SALAM/sys_validation.py --mem-size=4GB --mem-type=DDR4_2400_8x8 --kernel=/scratch/ayush/test/gem5-SALAM/benchmarks/sys_validation/stencil2d/sw/main.elf --disk-image=/scratch/ayush/test/gem5-SALAM/baremetal/common/fake.iso --machine-type=VExpress_GEM5_V1 --dtb-file=none --bare-metal --cpu-type=DerivO3CPU --accpath=/scratch/ayush/test/gem5-SALAM/benchmarks/sys_validation --accbench=stencil2d --caches --l2cache
Global frequency set at 1000000000000 ticks per second
warn: DRAM device capacity (16384 Mbytes) does not match the address range assigned (4096 Mbytes)
info: kernel located at: /scratch/ayush/test/gem5-SALAM/benchmarks/sys_validation/stencil2d/sw/main.elf
Cycle Counts Loaded!
Cycle Counts Loaded!
system.vncserver: Listening for connections on port 5900
system.terminal: Listening for connections on port 3456
warn: CoherentXBar system.acctest.coherency_bus has no snooping ports attached!
0: system.remote_gdb: listening for remote gdb on port 7000
**** REAL SIMULATION ****
warn: Existing EnergyCtrl, but no enabled DVFSHandler found.
info: Entering event queue @ 0.  Starting simulation...
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
 Current power model supports accelerators running at 1, 2, 3, 4, 5, 6, and 10 ns.
 Cycle time: 48 is not supported yet. Use 6ns power model instead.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/ARM/python/m5/main.py", line 457, in main
    exec(filecode, scope)
  File "configs/SALAM/sys_validation.py", line 393, in <module>
    Simulation.run(options, root, test_sys, FutureClass)
  File "/scratch/ayush/test/gem5-SALAM/configs/common/Simulation.py", line 726, in run
    exit_event = benchCheckpoints(options, maxtick, cptdir)
  File "/scratch/ayush/test/gem5-SALAM/configs/common/Simulation.py", line 269, in benchCheckpoints
    exit_event = m5.simulate(maxtick - m5.curTick())
  File "build/ARM/python/m5/simulate.py", line 180, in simulate
    return _m5.event.simulate(*args, **kwargs)
IndexError: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

I am not able to figure out how to handle this error, can you please suggest anything!

Regards
Ayush

**Comment by Josh-Slycord** [comment]
Hello Ayush!

Thank you for trying out gem5-SALAM, I'll look into these errors and get
back to you with a solution as soon as I can.

**Comment by samerogers** [comment]
Could you provide your version of g++ used to build SALAM with? Also which LLVM version are you using to compile the IR?

**Comment by ayush-upc** [comment]
Thank you for your response!
g++ --version 
10.1.0
llvm-config --version 
12.0.0git

**Comment by Josh-Slycord** [comment]
LLVM 3.8.1 must be used for generation of the IR files. Later versions change the structure of the IR, which likely caused the parser to read incorrectly, resulting in a empty vector, which caused your error. We are currently improving the parser to include a wrapper that utilities the LLVM library for parsing, like when writing an optimization pass, but it is still under development.

**Comment by Josh-Slycord** [comment]
Going to close this issue, if you have any questions, comments, or additional issues please let us know.
