### ISSUE TITLE
Strange i found in SALAM-Configurator/parser.py

### ISSUE THREAD

**Issue by Ivecia** [TeCSAR-UNCC/gem5-SALAM#23]
Hi, I'm wondering what the `i` refers to. I think it might be a bug.

https://github.com/TeCSAR-UNCC/gem5-SALAM/blob/c14c39235f4e376e64dc68b81bd2447e8a47ff65/SALAM-Configurator/parser.py#L218-L224

**Comment by zephan-spencer** [comment]
Very much an unintentional bug. I've gone ahead and commented it out as I don't believe I've ever used the other case.
Currently the fix lives [here](https://github.com/TeCSAR-UNCC/gem5-SALAM/blob/configurator_upgrade/tools/SALAM-Configurator), but I'll be pushing it to main eventually.
