### ISSUE TITLE
pipeline

### ISSUE THREAD

**Issue by chensx00** [TeCSAR-UNCC/gem5-SALAM#25]
May I ask if it supports building pipeline levels for accelerators？

**Comment by zephan-spencer** [comment]
I’m not too familiar with that term. Could you elaborate a little more on pipeline levels?

**Comment by chensx00** [comment]
What I mean is similar to the function pipelining in HLS, but I just discovered that it has this ability. So the issue can be closed. 
I was dizzy when I looked at the code and didn't notice the expression about pipelline ; )
