### ISSUE TITLE
internal bus structure and configs

### ISSUE THREAD

**Issue by caglairmak** [TeCSAR-UNCC/gem5-SALAM#27]
Hi, 
I would like to change the bandwidth of the local bus and mem-busses and L2 cache parameters and see the effects on the system.
Config.yml says dma is conncted to local bus, but no config params are given. (ex. benchmark/sys_validation/gemm/config.yml)

1) systemvalidation.sh sets CACHE_OPTS="--caches --l2cache"
2) In fs_gemm.py cache is placed between ipbus and membus. But information on local bus is not given. Where does the local bus connection set?
        if args.caches or args.l2cache:
            # By default the IOCache runs at the system clock
            test_sys.iocache = IOCache(addr_ranges = test_sys.mem_ranges)
            test_sys.iocache.cpu_side = test_sys.iobus.mem_side_ports
            test_sys.iocache.mem_side = test_sys.membus.cpu_side_ports

3) In the generated ini file I see some parameters on local bus. (BM_ARM_OUT/sys_validation/gemm/config.ini)
Could you guide me to change these params, membus params and cache params as well?

[system.gemm_clstr.local_bus]
type=NoncoherentXBar
children=power_state
clk_domain=system.clk_domain
eventq_index=0
forward_latency=0
frontend_latency=1
header_latency=1
power_model=
power_state=system.gemm_clstr.local_bus.power_state
response_latency=1
use_default_range=false
width=2
cpu_side_ports=system.iobus.mem_side_ports[18] system.gemm_clstr.dma.cluster_dma system.gemm_clstr.top.local[0]
mem_side_ports=system.gemm_clstr.dma.pio system.gemm_clstr.top.pio system.gemm_clstr.gemm.pio system.gemm_clstr.matrix1.port system.gemm_clstr.matrix2.port system.gemm_clstr.matrix3.port

thanks,
Irmak

**Comment by zephan-spencer** [comment]
Hi, sorry for the confusion on the config file stuff, I'm planning on getting some extra documentation out in the near future that should help clear things up. 

The .ini files are holdovers from our previous iteration of the simulator and need to be cleaned up from these benchmarks as they're currently ignored.

I'd recommend looking [here](https://github.com/TeCSAR-UNCC/gem5-SALAM/tree/configurator_upgrade/benchmarks/sys_validation) for current usage. 

You'll see that the YAML doc has two segments, an "acc_cluster" which is going to turn into the gem5 python script (in your case fs_gemm.py and gemm.py).

https://github.com/TeCSAR-UNCC/gem5-SALAM/blob/415ca8b47331c23d09008da4d3a213de536a513c/benchmarks/sys_validation/bfs/config.yml#L2-L6

And a "hw_config" which is going to parameterize the defined accelerators.

https://github.com/TeCSAR-UNCC/gem5-SALAM/blob/415ca8b47331c23d09008da4d3a213de536a513c/benchmarks/sys_validation/bfs/config.yml#L50-L58

The local_bus is part of the AccCluster SimObject defined in src/hwacc/AccCluster.py

https://github.com/TeCSAR-UNCC/gem5-SALAM/blob/415ca8b47331c23d09008da4d3a213de536a513c/src/hwacc/AccCluster.py#L37-L39

Let me know if you have any more questions, the repo is currently a bit of a mess and we're working on cleaning it up.

**Comment by caglairmak** [comment]
Hi, I assume the cluster dma is connected the system via local bus.

In gemm.py @ buildgemm_clstr function:
	# Noncoherent DMA
	clstr.dma = NoncoherentDma(pio_addr=0x10020000, pio_size = 21, gic=gic, int_num=95)
	clstr.dma.cluster_dma = clstr.local_bus.cpu_side_ports

The local bus in the AccCLuster class has 2 byte width. 

I have modified the top.c in /gem5-SALAM/benchmarks/sys_validation/gemm/hw/top.c to measure the cycle time of 1 dma engine as follows:


	//Define Device MMRs
	volatile uint8_t  * GEMMFlags  = (uint8_t *)GEMM;
	volatile uint8_t  * DmaFlags   = (uint8_t  *)(DMA_Flags);
	volatile uint64_t * DmaRdAddr  = (uint64_t *)(DMA_RdAddr);
	volatile uint64_t * DmaWrAddr  = (uint64_t *)(DMA_WrAddr);
	volatile uint32_t * DmaCopyLen = (uint32_t *)(DMA_CopyLen);

	//Transfer Input Matrices
	//Transfer M1
	*DmaRdAddr  = m1_addr;
	*DmaWrAddr  = MATRIX1;
	*DmaCopyLen = mat_size;
	*DmaFlags   = DEV_INIT;
	//Poll DMA for finish
	while ((*DmaFlags & DEV_INTR) != DEV_INTR);
	return;

I have measured the cycle time for moving 64*64 int32 data (16384 bytes) from RAM to the accelerator for different DMA MaxReqSize and BufferSize values. 16384 byte / measured cycle time is more than **16** for buffer size 1024 and maxReqsize 64. It is not possible if the local bus width is 2 bytes. Does the local bus width change/overwritten somewhere else?

Here is my experiments:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Deniz/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Deniz/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


row*colomn | type | MaxReqSize | BufferSize | size | top cycles | size/top cycles
-- | -- | -- | -- | -- | -- | --
64*64 | int 32 | 64 | 128 | 16384 | 1766 | 9.277463194
64*64 | int 32 | 64 | 256 | 16384 | 1024 | 16
64*64 | int 32 | 64 | 512 | 16384 | 940 | 17.42978723
64*64 | int 32 | 64 | 1024 | 16384 | 926 | 17.69330454
64*64 | int 32 | 128 | 256 | 16384 | 1402 | 11.68616262
64*64 | int 32 | 32 | 256 | 16384 | 1122 | 14.60249554
32*32 | int 32 | 64 | 128 | 4096 | 520 | 7.876923077
16*16 | int 32 | 64 | 128 | 1024 | 170 | 6.023529412



</body>

</html>


thanks,

Irmak.

**Comment by caglairmak** [comment]
Hi again,
I assume dma is connected to iobus via:
/gem5-SALAM/configs/common/FSConfig.py
self.realview.attachIO(self.iobus) 

The block diagram of the accelerartor cluster and system is as follows:
![SALAMDiyagram drawio](https://github.com/TeCSAR-UNCC/gem5-SALAM/assets/37383349/431f135d-f8ce-48ca-a6c6-3e8baa87ad76)

Could we say DMA from ram to SPM is limited with local bus width (2 bytes)?
regards,
Irmak

**Comment by zephan-spencer** [comment]
Sorry for the delayed response here.

 /gem5-SALAM/configs/common/FSConfig.py is the wrong spot to look for the config setup for the system. 

There have been some updates to the structure of where the configs go quite recently, but if you're on the current head commit the config file will be located at /gem5-SALAM/configs/SALAM/gemm.py.

If you aren't on the latest, it'll be in /gem5-SALAM/configs/SALAM/generated/gemm.py

You should see the below code in the file setting the max_req_size and buffer_size params. 

```python
clstr.dma = NoncoherentDma(pio_addr=0x10020000, pio_size = 21, gic=gic, int_num=95)
clstr.dma.cluster_dma = clstr.local_bus.cpu_side_ports
clstr.dma.max_req_size = 64
clstr.dma.buffer_size = 128
clstr.dma.dma = clstr.coherency_bus.cpu_side_ports
clstr.local_bus.mem_side_ports = clstr.dma.pio
```

Also, if you're interested in the connection layout those files get automatically generated if you have graphviz installed. Below is an example of the generated connection layout of the GEMM accelerator cluster.

![image](https://github.com/TeCSAR-UNCC/gem5-SALAM/assets/6306841/710a0543-ecef-404b-94a5-77f7066ee96c)

**Comment by zephan-spencer** [comment]
Closing for now, feel free to comment here if you want to continue the discussion.
