### ISSUE TITLE
Running gem5-SALAM using syscall emulation

### ISSUE THREAD

**Issue by ayush-upc** [TeCSAR-UNCC/gem5-SALAM#4]
Hi there,
does gem5-SALAM only works over full system emulation or can we use syscall emulation as well. If yes, please let me know the process, how I can use gem5-SALAM with syscall emulation.

**Comment by Jsslycord** [comment]
Currently we only provide support for full system emulation.

**Comment by samerogers** [comment]
gem5-SALAM is compatible with Syscall Emulation. You will still need to manually map the memory-mapped registers of any accelerators into the virtual memory address space of Syscall Emulation. Check configs/SALAM/hwacc.py for an example of declaring accelerators in the Python interface.

**Comment by ashriram** [comment]
If  SALAM is not intended to be used in syscall emulation, please let me know and ignore the questions below.
Can you elaborate a bit more please. I am trying to set this up for a course.
1.  Are the workloads statically linked and bare metal? 
2. I am not familiar with how gem5's syscall emulation maps the memory space. The hwacc seems to create a physical memory map. 
"map the memory-mapped registers of any accelerators into the virtual memory address space of Syscall Emulation".  How would you achieve this? Is it just a case of ensuring configurations match. Is baremetal.sh the appropriate script to start from ?
Thanks
