### ISSUE TITLE
Benchmarks failing sys validation

### ISSUE THREAD

**Issue by ashriram** [TeCSAR-UNCC/gem5-SALAM#9]
Hi ---

Gemm seems to be failing sys validation.

system.vncserver: Listening for connections on port 5900
system.terminal: Listening for connections on port 3456
warn: CoherentXBar system.acctest.coherency_bus has no snooping ports attached!
0: system.remote_gdb: listening for remote gdb on port 7000
**** REAL SIMULATION ****
warn: Existing EnergyCtrl, but no enabled DVFSHandler found.
info: Entering event queue @ 0.  Starting simulation...
panic: Address 1002f415800 is not reachable by any ports
Memory Usage: 4459896 KBytes
Program aborted at tick 3556260000
-------------------------------------------
Stencil2d output seems is incorrect. However the simulation runs to completion.
Any ideas?

**Comment by zephan-spencer** [comment]
Hi Arrvindh, 

Can you share a bit more about your current setup (OS and LLVM Version) and the steps to replicate the issue? 
I can't seem to replicate the issue on my end... 

Thank you,
Zephan

**Comment by ashriram** [comment]
Hi Zephan ---

See steps below to replicate. Please email me (if you want access to the actual machine or want a tar of the .ll files. ashriram@cs.sfu.ca. I was unable to find your email)

I have set up LLVM 3.8.1. Ubuntu 18.04
Branch: master
git clone https://github.com/TeCSAR-UNCC/gem5-SALAM
cd gem5-SALAM    
scons build/ARM/gem5.opt -j`nproc` 
export M5_PATH=$PWD

# FAILS
cd benchmarks/sys_validation
make
cd $M5_PATH 
./systemValidation.sh -b gemm (address out of range)
./systemValidation.sh -b stencil2d (incorrect results; fails checks in .terminal output)

This appears to be like an issue with either the host code or some issue with config.ini within sys_validation/

The gemm in benchmarks/ works (see below). However that appears to use a scratchpad. 

# PASSES
cd benchmarks/gemm
make
cd $M5_PATH
./baremetalarm.sh -b gemm

**Comment by samerogers** [comment]
Could you attach a version of your top.ll and gemm.ll? They can be found in benchmarks/sys_validation/gemm/hw. I was unable to recreate the error in a freshly downloaded repo.
